ProTwo/ProTwo/urls.py
from django.contrib import admin
from django.urls import path, include
from appTwo import views

urlpatterns = [
    path('',views.index,name='index')
    path('', include('appTwo.urls')),
    path('admin/', admin.site.urls),
]

advcbv/urls.py
from django.contrib import admin,include
from django.urls import path
from basic_app import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.IndexView.as_view()),
    path('basic_app/',include('basic_app.urls',namespace='basic_app'))
]

basicforms/basicforms/urls.py
from django.urls import path
from django.contrib import admin
from basicapp import views

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('formpage/',views.form_name_view,name='form_name')
]

protwo/protwo/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from apptwo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('first_app/', include('first_app.urls')),
    path('', views.index, name='index'),
]

templates/basic_app/urls.py
from django.conf.urls import path
from advance_section.basic_app.views import SchoolCreateView
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('',views.SchoolListView.as_view(),name='list')
    path('(?P<pk>[-\w +)/$', views.SchoolDetailView.as_view(),name='detail')
    path('create/$',views.SchoolCreateView.as_view(),name='create')
    path('update/(?P<pk>\d+)/$', views.SchoolUpdateView.as_view(),name='update'),
    path('delete/(?P<pk>[-\w +)/$', views.SchoolDeletelView.as_view(),name='delete')
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>

    <nav class="navbar navbar-default navbar-static-top">
        <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="{% url 'basic_app:list'%}">School</a></li>
            <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
            <li><a href="#"></a></li>
        </ul>

    </nav>


    <div class="container"></div>
    {% block body_block%}
    {% endblock %}
    
    </div>
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% block body_block %}
    <div class="jumbotron">
        <h1>Home Page!</h1>
    </div>
{% endblock %}